version: 2.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Build Stage"
          command: "docker build -t someimage -f Dockerfile.dev ."
workflows:
  say-hello-workflow:
    jobs:
      - build
