version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "test docker version"
          command: "docker -vvvv some"
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: "Build DEV"
          command: "docker build -t someimage -f Dockerfile.dev ."

workflows:
  say-hello-workflow:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: main

