version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: "test docker version"
          command: "docker -v"
      - run:
          name: "Build prod"
          command: "docker build -t someimage ."
      - run:
          name: "Build Stage"
          command: "docker build -t someimage -f Dockerfile.dev ."

workflows:
  say-hello-workflow:
    jobs:
      - build
