version: 2.1
jobs:
  build:
    docker:
      - image: node:10
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
workflows:
  say-hello-workflow:
    jobs:
      - build
